
### update
PUT http://localhost:5000/api/users/67bc4e3510431361617ed9aa
Content-Type: application/json

{
 
  
  "gold":
}

### tambah user baru
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "username":111,
  "level": 5,
  "energy": 150,
  "gold": 1000
}

### Hapus user
DELETE http://localhost:5000/api/users/67bf4cd26368829821f4b6d0


### Tes Register
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "username": "player1",
  "password": "123456"
}


### Test login
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "username": "player1",
  "password": "123456"
}


### Hanya jika login
GET http://localhost:5000/api/users
Authorization: Bearer <eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2MxMWEwNmI4Y2NlMGMzN2JkOWUwOGUiLCJpYXQiOjE3NDA3MTA1NTUsImV4cCI6MTc0MDcxNDE1NX0.21X0eBL3IuDqKJe7RN6yrflI6-EYoBFL9kfYofnfdbg>
